import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const iconsDir = path.join(__dirname, '../src/icons')
const indexPath = path.join(iconsDir, 'index.js')

// Read all icon files
const files = fs.readdirSync(iconsDir)
  .filter(f => f.endsWith('.jsx'))
  .map(f => f.replace('.jsx', ''))
  .sort()

console.log(`Found ${files.length} icons`)

// Categorize icons
const categories = {
  'Activity': files.filter(f => f.startsWith('Activity')),
  'Arrows': files.filter(f => f.startsWith('Arrow')),
  'Content': files.filter(f => f.startsWith('Content') || ['Add', 'Check', 'Copy', 'Delete', 'Download', 'Edit', 'Upload'].includes(f)),
  'Control': files.filter(f => f.startsWith('Control')),
  'Discovery': files.filter(f => f.startsWith('Discovery')),
  'Document': files.filter(f => f.startsWith('Document')),
  'Event': files.filter(f => f.startsWith('Event')),
  'Help': files.filter(f => f.startsWith('Help')),
  'Logo': files.filter(f => f.startsWith('Logo')),
  'Media': files.filter(f => f.startsWith('Media')),
  'Menu': files.filter(f => f.startsWith('Menu') || ['Close', 'Home', 'More', 'Search', 'Menu'].includes(f)),
  'Notice': files.filter(f => f.startsWith('Notice')),
  'Person': files.filter(f => f.startsWith('Person') || f === 'Person'),
  'Place': files.filter(f => f.startsWith('Place')),
  'Social': files.filter(f => f.startsWith('Social') || ['Like', 'Share'].includes(f)),
  'Thing': files.filter(f => f.startsWith('Thing') || ['Calendar', 'Info', 'Settings'].includes(f)),
  'Tree': files.filter(f => f.startsWith('Tree'))
}

// Generate index content
let content = '// Auto-generated icon exports\n// Generated by scripts/generateIconIndex.js\n\n'

Object.entries(categories).forEach(([category, icons]) => {
  if (icons.length === 0) return

  content += `// ${category}\n`
  icons.forEach(icon => {
    content += `export { ${icon} } from './${icon}'\n`
  })
  content += '\n'
})

fs.writeFileSync(indexPath, content)

console.log(`Generated index.js with ${files.length} exports`)
console.log('Categories:')
Object.entries(categories).forEach(([category, icons]) => {
  if (icons.length > 0) {
    console.log(`  ${category}: ${icons.length}`)
  }
})
